version: '3.8'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - ./src/hotel:/app/src/hotel
      - flask_migrations:/app/src/hotel/migrations
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hotel
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  flask_migrations:
